# Minifolio
# Example docker-compose.yml
#
# Usage:
# * The data directory will be set up inside `./data` on the host system
# * The private_data directory will be set up inside `./private_data` on the
#   host system.
# * You should create a `.env` file to contain the `AUTH_SECRET` environment
#   variable. Perhaps you could generate this using the command here:
#   https://unix.stackexchange.com/a/476125/161355
#
# It is not necessary to set up other environment variables
services:
  minifolio:
    # To build from the local repo, rather than the latest published version:
    # Comment out this line
    image: maddyguthridge/minifolio
    # And uncomment these lines
    # build:
    #   context: .
    #   ssh:
    #     - default

    hostname: minifolio
    restart: always
    ports:
      - 127.0.0.1:3000:3000/tcp
    volumes:
      - "./data:/data:rw"
      - "./private_data:/private_data:rw"

    environment:
      DATA_REPO_PATH: "/data"
      PRIVATE_DATA_PATH: "/data"
      HOST: 0.0.0.0
      PORT: 3000
    # Set up `AUTH_SECRET` variable within `.env`
    env_file: ".env"
